Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2024-04, with the labels that each got.

#260 feat: Allow empty lines to be used as selection as well
  lua/CopilotChat/select.lua
Labels: enhancement

#264 fix: Authenticate asynchronously instead of blocking the editor
  lua/CopilotChat/copilot.lua
Labels: bug

#266 feat: Send whole content of small files in @buffers as well
  lua/CopilotChat/context.lua
Labels: enhancement

#268 fix: Check if github token file is readable and exists
  lua/CopilotChat/copilot.lua
Labels: bug

#270 docs: Match README config with config.lua
  README.md
Labels: documentation

#269 fix: Check if key has any mapping before showing help
  lua/CopilotChat/init.lua
Labels: bug

#273 fix: Use latest vscode copilot headers
  lua/CopilotChat/copilot.lua
Labels: bug

#272 fix: Handle error responses from copilot properly
  lua/CopilotChat/copilot.lua
Labels: bug

#274 feat: Update Copilot prompts to same one as vs code uses
  lua/CopilotChat/prompts.lua
Labels: enhancement

#276 feat(copilot): load GitHub token from environment
  lua/CopilotChat/copilot.lua
Labels: enhancement

#280 feat: Normalize generation prompts, add Review prompt, use more vscode prompts
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#282 feat: allow height and width for horizontal and vertical
  README.md
  lua/CopilotChat/chat.lua
  lua/CopilotChat/config.lua
Labels: enhancement

#293 feat: Remove confusing double wrapping from chat
  lua/CopilotChat/chat.lua
Labels: enhancement
