Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2024-12, with the labels that each got.

#656 docs: Improve README structure so generated vimdoc is better
  .github/workflows/ci.yml
  README.md
Labels: enhancement

#658 refactor(prompt): improve config handling in resolve_prompts
  lua/CopilotChat/init.lua
Labels: enhancement

#659 docs: add config retrieval example to README
  README.md
Labels: documentation

#660 docs: Update badges and remove migration guide mention as its old
  README.md
Labels: documentation

#661 docs: cleanup some vimdoc issues in README
  README.md
Labels: documentation

#662 fix: correct badge links in README.md
  README.md
Labels: bug, documentation

#663 docs: Remove toc
  README.md
Labels: documentation

#666 docs: add mention about clause availability
  README.md
Labels: documentation

#668 docs: update list of customizable buffers
  README.md
Labels: documentation

#669 ci: update pandoc workflow to run on main branch
  .github/workflows/ci.yml
Labels: bug

#671 fix: improve stream parsing and error handling
  lua/CopilotChat/copilot.lua
Labels: bug, enhancement

#673 refactor: optimize context handling and content blocks
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/ui/debug.lua
Labels: enhancement

#678 Remove fail with body curl args
  lua/CopilotChat/copilot.lua
Labels: enhancement

#679 fix: correct chat config handling
  lua/CopilotChat/init.lua
Labels: bug

#682 fix: refactor ask function to handle content properly
  lua/CopilotChat/copilot.lua
Labels: bug

#685 fix: add default empty table for state.source
  lua/CopilotChat/init.lua
Labels: bug
