Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2024-03, with the labels that each got.

#112 fix: Properly handle splits on neovim stable
  lua/CopilotChat/init.lua
Labels: bug

#114 fix; Focus window on ask properly
  lua/CopilotChat/init.lua
Labels: bug

#116 fix: Use proper config for selection and update selection earlier
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
Labels: bug

#110 feat: Add support for embeddings
  .editorconfig
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/debuginfo.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/prompts.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#131 feat: Make integrations more extendable and add fzf-lua
  MIGRATION.md
  README.md
  lua/CopilotChat/actions.lua
  lua/CopilotChat/code_actions.lua
  lua/CopilotChat/integrations/fzflua.lua
  lua/CopilotChat/integrations/telescope.lua
Labels: enhancement

#134 feat: Improve diff display and optimize existing prompts for diffs
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/prompts.lua
  lua/CopilotChat/spinner.lua
Labels: enhancement

#135 fix: Handle missing TS parsers gracefully, handle TS aliases
  lua/CopilotChat/context.lua
Labels: bug

#144 fix: Check if diff treesitter parser exists
  lua/CopilotChat/diff.lua
Labels: bug

#147 feat: Improve healthcheck messages with fix instructions
  lua/CopilotChat/health.lua
Labels: enhancement

#151 fix: Check if we are on nightly when setting chat footer
  lua/CopilotChat/chat.lua
Labels: bug

#152 chore: Add CONTRIBUTING.md
  CONTRIBUTING.md
  structure.drawio
Labels: documentation

#153 chore: Add spoilers for tips and make Configuration top level section
  README.md
Labels: documentation

#149 feat: Add SHOW_CONTEXT prompt
  lua/CopilotChat/prompts.lua
Labels: enhancement

#150 feat: Send whole file instead of outline for @buffer
  lua/CopilotChat/context.lua
Labels: enhancement

#154 fix: Gracefully handle errors from copilot
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: bug

#157 fix: Improve boundary checks around last position in buffer
  lua/CopilotChat/chat.lua
Labels: bug

#159 fix: Validate if buffer is loaded and if buffer has lines
  lua/CopilotChat/chat.lua
Labels: bug

#166 fix; Null check spinner when closing chat
  lua/CopilotChat/chat.lua
Labels: bug

#172 feat: Switch from virt text to virt lines for help
  lua/CopilotChat/chat.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/spinner.lua
Labels: enhancement

#177 fix: Remove concealcursor configuration
  lua/CopilotChat/chat.lua
  lua/CopilotChat/debuginfo.lua
Labels: bug

#179 fix: Use temp files when making curl requests
  lua/CopilotChat/copilot.lua
Labels: enhancement

#176 feat: Move system prompt and current selection to separate overlays in chat
  MIGRATION.md
  README.md
  lua/CopilotChat/chat.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
  lua/CopilotChat/spinner.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#182 fix: Avoid using vim functions for managing temp files
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/utils.lua
Labels: bug

#185 fix: Improve stability of job cancellation and chat reset
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/spinner.lua
Labels: bug

#180 feat: Save and load chat history
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#186 fix: Fix diff highlights for overlays
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
Labels: bug

#189 feat: Add back option to hide help
  MIGRATION.md
  README.md
  lua/CopilotChat/chat.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#193 Revert "Use method overriding for defining buf_create logic for overl…
  lua/CopilotChat/chat.lua
  lua/CopilotChat/overlay.lua
Labels: bug

#201 docs: Make configuration easier to navigate through
  README.md
  lua/CopilotChat/config.lua
Labels: documentation

#202 feat: Show token count as virtual line instead of in buffer
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#204 203 add custom mappings
  README.md
  lua/CopilotChat/init.lua
Labels: enhancement

#212 docs: Add example for .response() also to API section
  README.md
Labels: documentation

#211 feat: Add option to auto enter insert mode
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#210 fix: Use prompt selection when picking prompts
  lua/CopilotChat/actions.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/integrations/fzflua.lua
  lua/CopilotChat/integrations/telescope.lua
Labels: bug

#213 fix: Add back option to configure selection for picker actions
  MIGRATION.md
  README.md
  lua/CopilotChat/actions.lua
Labels: bug

#216 feat: Add insert mode mappings as well
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#223 fix: Properly start insert mode on opening window, regardless of source
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
Labels: bug

#217 feat: Add start and end line number as line range to active selection
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#226 fix: Warn users about configuration cchange and do not break plugin
  .github/workflows/ci.yml
  lua/CopilotChat/init.lua
Labels: bug

#219 feat: Add source parameter to callback function
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#229 feat: Set chat and overlay filetypes to their names
  lua/CopilotChat/chat.lua
  lua/CopilotChat/overlay.lua
Labels: enhancement

#236 feat: Make question/answer/error headers configurable
  MIGRATION.md
  README.md
  lua/CopilotChat/chat.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#237 feat: Do not push help and tokens to left column
  lua/CopilotChat/utils.lua
Labels: enhancement

#242 fix: Check for empty strings when defining keymaps
  lua/CopilotChat/init.lua
Labels: bug

#238 Feature: Add Action to Yank Response to Register
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#241 Remove "done!" notification
  lua/CopilotChat/spinner.lua
Labels: good first issue

#247 fix: Remap bindings to not conflict with terminal
  lua/CopilotChat/config.lua
Labels: bug

#255 feat: Add check for supported nightly versions of neovim
  lua/CopilotChat/health.lua
Labels: enhancement

#254 fix: Properly check if window layout changed before resetting
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: bug
