Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2024-11, with the labels that each got.

#447 Grab model data dynamically instead of hardcoded
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/tiktoken.lua
Labels: enhancement

#449 Insert content to history properly on non-streamed response
  lua/CopilotChat/copilot.lua
Labels: bug

#450 Improve model listing and add info about :CopilotChatModels to config
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/tiktoken.lua
Labels: enhancement

#454 Remove GPT-4 forcing from system prompt
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#458 Use vim.cmd instead of feed keys for exiting visual mode
  lua/CopilotChat/utils.lua
Labels: bug

#459 Improve tiktoken download paralellization
  lua/CopilotChat/tiktoken.lua
Labels: bug, enhancement

#467 Automatically sanitize input sent to copilot API
  lua/CopilotChat/copilot.lua
Labels: bug, enhancement

#471 Use plenary.async instead of callback hell
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#473 Fix tests failing on plenary.async
  test/plugin_spec.lua
Labels: bug

#474 Fix missing plenary.wrap in tests
  test/plugin_spec.lua
Labels: bug

#472 Add config for setting log level
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#475 Improve job cancellation
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#478 Add handling for no response from stream and improve curl performance
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#479 Add max_tokens to chat requests
  lua/CopilotChat/copilot.lua
Labels: enhancement

#481 Improve help display
  lua/CopilotChat/init.lua
Labels: enhancement

#482 Automatically clear copilot diagnostics on asking new question
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#483 Fix error matching
  lua/CopilotChat/init.lua
Labels: bug

#484 Add separators when showing diff/prompt/selection windows
  lua/CopilotChat/init.lua
Labels: enhancement

#485 Load github token asynchronously
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/overlay.lua
  lua/CopilotChat/spinner.lua
Labels: bug, enhancement

#486 Send code 0 in shutdown to propagate error message properly
  lua/CopilotChat/copilot.lua
Labels: bug

#487 Revamp how diagnostics are handled
  README.md
  lua/CopilotChat/actions.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#488 refactor(commit): consolidate commit commands into one
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
Labels: enhancement

#489 Show only error message from curl instead of whole object
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#492 Increase flexibility of diff selectors
  lua/CopilotChat/init.lua
Labels: enhancement

#493 Automatically register copilot-chat for treesitter markdown
  README.md
  lua/CopilotChat/chat.lua
Labels: enhancement

#490 Add support for copilot extension agents
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/integrations/cmp.lua
Labels: enhancement

#491 Adjust how messages are built to match new vscode requests
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#496 Add agent descriptions to autocomplete
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#495 Add support for #files (workspace file map) context
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/debuginfo.lua
  lua/CopilotChat/health.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#498 style: improve model/agent selection prompts
  lua/CopilotChat/init.lua
Labels: enhancement

#500 Remove private fields from chat class type definition
  lua/CopilotChat/chat.lua
Labels: enhancement

#502 Add option to disable header highlighting
  README.md
  lua/CopilotChat/chat.lua
  lua/CopilotChat/config.lua
Labels: enhancement

#503 Add support for sticky prompt section with `> `
  README.md
  lua/CopilotChat/chat.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#505 Simplify how source buffer is being saved and unify prompt clearing
  lua/CopilotChat/init.lua
Labels: enhancement

#506 feat(context): rewrite context system with input and resolving
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/debuginfo.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
Labels: enhancement

#508 docs: add missing help for model selection
  lua/CopilotChat/init.lua
Labels: documentation

#509 docs: improve documentation for contexts and complete binding
  README.md
  lua/CopilotChat/config.lua
Labels: documentation

#510 Fix loading of default context
  lua/CopilotChat/init.lua
Labels: bug

#511 Load chat auto_insert from config instead of passing it in contructor
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#507 feat: add automatic chat autocompletion
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/integrations/cmp.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#512 Include filenames in buffer context selection, improve buffers context
  README.md
  lua/CopilotChat/config.lua
Labels: enhancement

#514 refactor: improve semantic embeddings performance
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#515 perf: add caching for embeddings
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
Labels: enhancement

#516 docs: improve README with better examples and cleaner structure
  README.md
  lua/CopilotChat/init.lua
Labels: documentation

#517 Use relative paths for file references in contexts
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
Labels: enhancement

#518 Explicitely mention that multiple contexts are supported in README
  README.md
Labels: documentation

#519 Add documentation for selections to README
  README.md
Labels: documentation

#520 Add table of contents to README because of all new config sections
  README.md
Labels: documentation

#521 Show errors inline in response
  README.md
  lua/CopilotChat/init.lua
Labels: enhancement

#523 refactor: improve diff handling implementation
  lua/CopilotChat/chat.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
  lua/CopilotChat/prompts.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#525 refactor(context): improve accuracy of buffer processing
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/debuginfo.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#529 Standardize context embedding format
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
Labels: enhancement

#530 docs: Use content instead of lines in custom selector example
  README.md
Labels: documentation

#532 Do not stop spinner on closing window
  lua/CopilotChat/chat.lua
Labels: bug

#533 refactor: improve buffer validation and diff handling
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
  lua/CopilotChat/spinner.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#534 refactor(select): simplify visual line selection
  lua/CopilotChat/select.lua
Labels: bug, enhancement

#535 fix: add validity checks for file and buffer functions
  lua/CopilotChat/context.lua
Labels: bug

#536 fix: check if in insert mode before showing completions
  lua/CopilotChat/init.lua
Labels: bug

#537 fix(select): ensure diagnostics are passed to the model when in "Visual"
  lua/CopilotChat/select.lua
Labels: bug

#539 feat: truncate large files and improve context output
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/prompts.lua
  lua/CopilotChat/select.lua
Labels: bug, enhancement

#540 fix: make header pattern matching more robust
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#541 fix: fix o1-preview non-streaming response parsing
  lua/CopilotChat/copilot.lua
Labels: bug

#543 refactor: improve selection handling and highlighting
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#544 feat: support header diff matching without selection
  lua/CopilotChat/init.lua
Labels: enhancement

#545 feat: add jump to diff feature with `gj` mapping
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#546 fix: Set jump marks safely after diff jumping
  lua/CopilotChat/init.lua
Labels: bug

#547 chore: add extra newline when showing system prompt and selection
  lua/CopilotChat/init.lua
Labels: enhancement

#548 feat: add quickfix list for code blocks in chat
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#549 refactor: cleanup selection state management
  lua/CopilotChat/init.lua
Labels: enhancement

#553 docs: Add documentation about chat mappings and README image
  README.md
Labels: documentation

#555 Mention that visual selections include diagnostics as well in README
  README.md
Labels: documentation

#556 feat(chat): add no_chat option
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#559 refactor(prompts): improve diagnostics handling system
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/prompts.lua
Labels: enhancement

#560 refactor: remove redundant treesitter parser init
  lua/CopilotChat/chat.lua
Labels: enhancement

#562 Make insert complete mapping accept completion if pum is visible
  lua/CopilotChat/init.lua
Labels: enhancement

#564 docs: improve readme for mappings
  README.md
  lua/CopilotChat/init.lua
Labels: enhancement

#566 refactor: move utility functions to utils module
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#567 Make policy enabling generic
  lua/CopilotChat/copilot.lua
Labels: enhancement

#569 feat: add proc/template/macro declaration support
  lua/CopilotChat/context.lua
Labels: enhancement

#571 feat: support for markdown outlines
  lua/CopilotChat/context.lua
Labels: enhancement

#572 fix: improve chat buffer rendering and state handling
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
Labels: enhancement

#573 fix: rerender chat after opening as well
  lua/CopilotChat/chat.lua
Labels: bug

#574 refactor: improve chat output parsing and selection handling
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#568 feat: add register context and improve selection handling
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
Labels: enhancement

#575 refactor: improve class extending system
  lua/CopilotChat/chat.lua
  lua/CopilotChat/diff.lua
  lua/CopilotChat/overlay.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#576 fix: improve selection validation checks
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#578 feat: add show context command for Copilot Chat
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
Labels: enhancement

#583 feat: add buffer validation for chat window
  lua/CopilotChat/chat.lua
Labels: bug, enhancement

#588 feat(chat): set default completion options for chat buf
  lua/CopilotChat/chat.lua
Labels: enhancement

#589 refactor: improve embedding handling with ordered map
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#590 fix: guard completeopt setting behind nvim-0.11.0 check
  README.md
  lua/CopilotChat/chat.lua
Labels: bug

#591 fix: set completeopt on window opening and properly guard behind config
  lua/CopilotChat/chat.lua
Labels: bug, enhancement

#592 fix: improve window CWD handling
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#593 refactor: use cwd from dir changed event
  lua/CopilotChat/init.lua
Labels: enhancement

#594 fix: improve chat prompt clearing and cwd detection
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#596 fix: also use dirchanged for tracking win dir on top of winenter
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#597 perf: optimize chat section detection
  lua/CopilotChat/chat.lua
Labels: enhancement

#598 feat: improve help display and token count visibility
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/overlay.lua
  lua/CopilotChat/spinner.lua
Labels: enhancement

#599 fix: improve chat window handling and auto-insert behavior
  lua/CopilotChat/chat.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#600 fix: properly parse prompts
  lua/CopilotChat/init.lua
Labels: bug

#601 refactor(types): improve type safety and organization
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/ui/debug.lua
  lua/CopilotChat/ui/diff.lua
  lua/CopilotChat/ui/overlay.lua
  lua/CopilotChat/ui/spinner.lua
  lua/CopilotChat/utils.lua
Labels: documentation, enhancement

#602 refactor: extract debug info content retrieval outside of class
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/debug.lua
Labels: enhancement

#603 fix(selection): properly pass chat config to functions
  lua/CopilotChat/init.lua
Labels: enhancement

#604 refactor: improve prompt resolution handling and cleanup types
  README.md
  lua/CopilotChat/actions.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#605 feat: sort completion items by kind and word
  lua/CopilotChat/init.lua
Labels: enhancement

#606 refactor(config): split config into static and shared parts properly
  README.md
  lua/CopilotChat/actions.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#607 refactor(config): reorganize shared/static config fields
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: bug, enhancement

#608 fix: use correct function name for deprecation
  lua/CopilotChat/select.lua
Labels: bug

#609 refactor: move embed truncation logic to proper places
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/ui/overlay.lua
  lua/CopilotChat/ui/spinner.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#611 fix: improve prompt embedding and ranking
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#612 refactor(context): simplify outline building and add typing
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
Labels: enhancement

#613 refactor: simplify context filtering and ranking
  lua/CopilotChat/context.lua
Labels: enhancement

#615 fix: improve sticky prompt handling and section detection
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: bug

#616 refactor: migrate to uv async for file operations
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#617 refactor: optimize vim scheduler usage in chat module
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
  test/plugin_spec.lua
Labels: enhancement

#618 refactor(mappings): improve key mapping API and descriptions
  lua/CopilotChat/init.lua
Labels: enhancement

#622 fix: add debug logging for Copilot HTTP responses
  lua/CopilotChat/copilot.lua
Labels: enhancement

#624 fix: make file operations and contexts async
  .luarc.json
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#625 refactor(context): replace io.popen with vim.system
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#626 perf: optimize GitHub token handling and remove scheduler
  lua/CopilotChat/copilot.lua
Labels: enhancement

#627 feat(context): add full file content support for files
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#630 refactor(copilot): improve embedding reliability
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
Labels: enhancement

#634 fix: improve debug info window handling
  lua/CopilotChat/context.lua
  lua/CopilotChat/ui/debug.lua
Labels: bug

#635 refactor(context): optimize file loading with caching
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
  lua/CopilotChat/ui/debug.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#636 refactor: simplify buffer handling using builtin functions
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#638 fix: improve logging output format and consistency
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#639 fix: add error handling to chat async operation
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#640 refactor: unify info display into show_info and show_context
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#641 fix: add null check for buffer symbols
  lua/CopilotChat/ui/debug.lua
Labels: bug

#642 style: improve debug output readability
  lua/CopilotChat/ui/debug.lua
Labels: enhancement

#637 feat: add URL context support using lynx
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/health.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#644 docs(readme): reorganize requirements section
  README.md
Labels: documentation

#645 docs: improve README formatting and add prompt command info
  README.md
Labels: documentation

#646 refactor: switch to character-based truncation
  lua/CopilotChat/copilot.lua
Labels: enhancement

#647 feat: add status notifications for background tasks
  lua/CopilotChat/context.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/notify.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/ui/spinner.lua
Labels: enhancement

#648 feat: make lynx optional for URL context
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/health.lua
Labels: enhancement

#649 style: link spinner highlight to DiagnosticInfo
  lua/CopilotChat/init.lua
Labels: enhancement

#651 refactor: move source type to init.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/select.lua
Labels: documentation

#652 Add vid to README
  README.md
Labels: documentation

#654 refactor(context): extract buffer list logic to new function
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
Labels: bug, enhancement

#655 docs: update files context name in README.md
  README.md
Labels: bug, documentation
