Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2025-08, with the labels that each got.

#1239 feat(health): add temp dir writable check
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/health.lua
Labels: enhancement

#1244 fix(chat): properly replace all message data when replacing message
  lua/CopilotChat/ui/chat.lua
Labels: bug

#1254 docs(README): use table for prompts as well
  README.md
Labels: documentation

#1256 docs(README): Fix duplicate headers
  README.md
Labels: bug, documentation

#1257 fix(functions): properly allow skipping handling for tools
  lua/CopilotChat/init.lua
Labels: bug

#1258 fix(chat): handle empty prompt and tools before ask
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#1259 fix(chat): handle skipped tool calls with explicit error result
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#1260 feat(ui): improve keyword highlights accuracy and performance
  README.md
  lua/CopilotChat/ui/chat.lua
  plugin/CopilotChat.lua
Labels: enhancement

#1265 feat(chat): improve error handling
  lua/CopilotChat/init.lua
Labels: enhancement

#1268 docs: mention selection in core concepts
  README.md
Labels: documentation

#1279 refactor(resources): unify resource format and handling
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/functions.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/resources.lua
Labels: enhancement

#1290 refactor(core): improve config handling and setup logic
  lua/CopilotChat/init.lua
Labels: enhancement

#1291 fix(client): store models cache per provider
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/utils.lua
Labels: bug

#1298 refactor(chat): unify message/block API for cursor access
  README.md
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#1299 feat(ui): show assistant reasoning as virtual text
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#1301 fix(chat): correct block selection logic by cursor
  lua/CopilotChat/ui/chat.lua
Labels: bug

#1302 refactor(constants): centralize role and plugin name constants
  lua/CopilotChat/client.lua
  lua/CopilotChat/completion.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/constants.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: refactor

#1312 refactor(prompts)!: support template substitution in system_prompt
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
Labels: refactor

#1325 fix(config): correct system_prompt type and callback usage
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/prompts.lua
Labels: bug

#1327 refactor(prompt): simplify system prompt resolution logic
  README.md
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
Labels: refactor

#1328 fix(completion): require tool uri for input completion
  lua/CopilotChat/completion.lua
Labels: bug

#1333 test: migrate to MiniTest and add utils tests
  .github/workflows/ci.yml
  .gitignore
  .luarc.json
  Makefile
  README.md
  scripts/minimal.lua
  scripts/test.lua
  test/plugin_spec.lua
  tests/test_init.lua
  tests/test_utils.lua
Labels: enhancement

#1336 test: add setup test for CopilotChat module
  .luarc.json
  tests/init_spec.lua
Labels: tests

#1337 test(functions): add unit tests for functions module
  tests/functions_spec.lua
  tests/init_spec.lua
Labels: tests

#1339 refactor(utils): remove custom glob to pattern logic
  lua/CopilotChat/utils.lua
  tests/utils_spec.lua
Labels: refactor

#1357 refactor(prompts): use resources instead of sticky for Commit
  lua/CopilotChat/config/prompts.lua
Labels: refactor

#1361 fix(select): move config inside of marks function to prevent import loop
  lua/CopilotChat/select.lua
Labels: bug

#1365 refactor(config): rename tool failure option for clarity
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: documentation, refactor

#1366 refactor(utils): split class, ordered map, string buffer
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/ui/overlay.lua
  lua/CopilotChat/ui/spinner.lua
  lua/CopilotChat/utils.lua
  lua/CopilotChat/utils/class.lua
  lua/CopilotChat/utils/orderedmap.lua
  lua/CopilotChat/utils/stringbuffer.lua
Labels: refactor

#1351 feat(functions): add scope=selection to diagnostics
  lua/CopilotChat/config/functions.lua
Labels: enhancement

#1367 refactor(utils): split file operation to utils.files
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/functions.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/resources.lua
  lua/CopilotChat/utils.lua
  lua/CopilotChat/utils/files.lua
Labels: refactor

#1370 feat(prompts): support buffer replacement in commit messages
  lua/CopilotChat/config/prompts.lua
Labels: enhancement

#1371 refactor(utils): split curl logic into separate module
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/resources.lua
  lua/CopilotChat/select.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/utils.lua
  lua/CopilotChat/utils/curl.lua
Labels: refactor

#1373 feat(functions): use cwd for file and grep commands
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/utils/files.lua
Labels: enhancement

#1375 refactor(core): simplify tool output formatting
  lua/CopilotChat/init.lua
Labels: refactor

#1376 refactor(core): split tool and function resolution logic
  README.md
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
Labels: refactor

#1378 fix(files): generate absolute paths in code blocks
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/utils/files.lua
Labels: bug

#1382 feat(tiktoken): improve token counting accuracy
  lua/CopilotChat/client.lua
  lua/CopilotChat/tiktoken.lua
Labels: enhancement

#1385 fix: Correct header highlighting for multi-byte characters
  lua/CopilotChat/ui/chat.lua
Labels: bug
