Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2025-03, with the labels that each got.

#887 fix: do not use vim.fs.abspath
  lua/CopilotChat/utils.lua
Labels: bug

#889 feat: use adaptive variant for Stargazers chart
  README.md
Labels: documentation

#890 refactor: streamline system prompts architecture
  README.md
  lua/CopilotChat/config/prompts.lua
Labels: enhancement

#891 refactor: reorder role first in prompts
  lua/CopilotChat/config/prompts.lua
Labels: enhancement

#892 feat(health): add setup check to health module
  lua/CopilotChat/health.lua
Labels: enhancement

#893 fix: clear config when resetting chat
  lua/CopilotChat/ui/chat.lua
Labels: bug, enhancement

#896 fix: prevent errors when accessing window config
  lua/CopilotChat/ui/chat.lua
Labels: bug

#897 fix(utils): `glob_to_regex` recursion matching
  lua/CopilotChat/utils.lua
Labels: bug

#900 feat(context): add system context for shell command output
  README.md
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#855 refactor!: centralize sticky prompt and selection handling
  README.md
  lua/CopilotChat/client.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#905 feat: allow diff accept to jump buffers like jump_to_diff
  lua/CopilotChat/config/mappings.lua
Labels: enhancement

#908 docs: update provider documentation and references
  README.md
Labels: documentation

#909 refactor(ui): centralize overlay and diff functionality
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/ui/diff.lua
  lua/CopilotChat/ui/overlay.lua
Labels: enhancement

#911 refactor(api): improve Chat class organization and privacy
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/ui/overlay.lua
  lua/CopilotChat/ui/spinner.lua
Labels: documentation

#912 feat: add remember_as_sticky config option
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#913 docs: update documentation after sticky key changes
  README.md
Labels: documentation

#914 docs(readme): update selections configuration info
  README.md
Labels: documentation

#915 docs: remove copilot-diff from README as it doesnt exist anymore
  README.md
Labels: documentation

#916 feat: allow per-chat selection configurations
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#918 docs(readme): update API reference with complete function list
  README.md
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
Labels: documentation

#919 feat!: mark async functions with annotations
  README.md
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#920 fix: eliminate reference duplication with ordered map
  lua/CopilotChat/client.lua
Labels: bug, enhancement

#921 feat: add description field to prompt items
  lua/CopilotChat/init.lua
Labels: enhancement

#922 fix: reset diagnostics when stopping Copilot Chat
  lua/CopilotChat/init.lua
Labels: enhancement

#923 docs: add missing system context to README
  README.md
Labels: documentation

#924 feat: add conversation memory summarization
  README.md
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#925 refactor(prompts): use proper fields for prompt settings
  README.md
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#926 feat: at least open chat when :CopilotChat input is empty
  lua/CopilotChat/init.lua
Labels: enhancement

#927 docs: show documentation also for close in chat
  lua/CopilotChat/config/mappings.lua
Labels: documentation

#928 refactor: clean up utils module structure and function format
  lua/CopilotChat/utils.lua
Labels: enhancement

#930 fix: add back uuid
  lua/CopilotChat/utils.lua
Labels: bug

#932 fix: correct history storage in client
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/mappings.lua
Labels: bug, enhancement

#933 feat: send diagnostics with buffer context as well
  lua/CopilotChat/client.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/select.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#934 fix: improve history updates safety
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/mappings.lua
Labels: bug

#935 refactor(memory): improve conversation memory management
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#936 fix: update reference handling in selection messages
  lua/CopilotChat/client.lua
Labels: enhancement

#938 feat: util method to add sticky prompt to chat
  README.md
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#939 fix: clear memory when resetting the client
  lua/CopilotChat/client.lua
Labels: bug

#940 fix: manually trigger BufEnter when restoring buffers
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/overlay.lua
Labels: bug

#941 fix(utils): optimize return to normal mode function
  lua/CopilotChat/utils.lua
Labels: enhancement

#942 fix: improve handling of empty responses
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#943 refactor: improve conversation history summarization
  lua/CopilotChat/client.lua
Labels: enhancement

#946 fix: ignore SSE comments in parsing stream response
  lua/CopilotChat/client.lua
Labels: bug

#947 refactor(chat): simplify section and block return values
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#948 fix: improve buffer handling in diff view
  lua/CopilotChat/config/mappings.lua
Labels: enhancement

#950 fix: properly split chat horizonatally/vertically when existing split…
  lua/CopilotChat/ui/chat.lua
Labels: bug

#951 feat: show source information in chat info panel
  lua/CopilotChat/config/mappings.lua
Labels: enhancement

#952 fix: improve source buffer selection for headless mode
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#953 feat(search)!: use ripgrep when available for file scanning
  README.md
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/health.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#954 fix: handle file listing limit properly
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/utils.lua
Labels: bug

#955 feat: improve default file scanning arguments
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#956 fix(readme): remove Tab mapping in normal mode for chat
  README.md
Labels: documentation

#957 fix: allow using system prompt name as string
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: bug

#958 refactor(ui): improve help message handling
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/ui/overlay.lua
Labels: enhancement

#959 refactor: move commands and highlights to plugin file
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
  plugin/CopilotChat.lua
Labels: enhancement

#960 fix: make second part of line matching in diffs optional
  lua/CopilotChat/ui/chat.lua
Labels: bug

#961 feat(chat): add multi-diff support
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#962 fix: remove debug print statements
  lua/CopilotChat/config/mappings.lua
Labels: bug

#963 feat(debug): add history info to debug output
  lua/CopilotChat/config/mappings.lua
Labels: enhancement

#965 fix: disable auto-completion without proper completeopt
  README.md
  lua/CopilotChat/init.lua
Labels: enhancement

#971 fix(error-handling): simplify error handling conditions
  lua/CopilotChat/init.lua
Labels: bug

#972 fix: filter nil values from modified array
  lua/CopilotChat/config/mappings.lua
Labels: bug

#973 feat: add context provider command helpers to prompt
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#974 feat(context): improve context help and code block handling
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#977 docs: update external provider references and add AI info
  README.md
Labels: documentation

#979 fix: guard against auth and API failures
  lua/CopilotChat/client.lua
Labels: bug

#980 refactor(context): simplify context handling with direct methods
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#983 refactor(context): standardize backtick syntax for providers
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/contexts.lua
Labels: enhancement

#984 feat(system): improve system command context error handling
  lua/CopilotChat/config/contexts.lua
Labels: enhancement

#987 feat: expose source buffer API and support disabling mappings
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#989 docs: improve context provider descriptions
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/contexts.lua
Labels: documentation

#990 refactor(prompt): improve context provider help text format
  lua/CopilotChat/client.lua
Labels: refactor

#993 docs: add back mention about popup to README
  README.md
Labels: documentation

#994 feat: support noselect completeopt setting
  README.md
  lua/CopilotChat/init.lua
Labels: bug

#996 refactor: expose COPILOT_BASE prompt as base prompt
  README.md
  lua/CopilotChat/config/prompts.lua
Labels: enhancement, refactor

#999 feat: use version map again for resolving all copilot models
  lua/CopilotChat/config/providers.lua
Labels: enhancement

#1001 fix: add error handling for context resolution
  .stylua.toml
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/health.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/ui/spinner.lua
  plugin/CopilotChat.lua
Labels: bug

#1002 fix: use ipairs when iterating over resolved embeddings
  lua/CopilotChat/init.lua
Labels: bug

#998 feat(chat): add streaming callback support
  README.md
  lua/CopilotChat/client.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#1004 refactor: improve headless mode handling
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#1005 refactor: optimize code outline generation with caching
  lua/CopilotChat/context.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#1006 feat(context): add async treesitter parsing support
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#1007 refactor(cache): improve embedding cache consistency
  lua/CopilotChat/context.lua
Labels: bug, enhancement

#1008 style: improve context provider help text formatting
  lua/CopilotChat/client.lua
Labels: enhancement

#1009 fix: improve error logging for failed context resolution
  lua/CopilotChat/init.lua
Labels: enhancement

#1010 feat: improve context provider completion display
  lua/CopilotChat/init.lua
Labels: enhancement

#1011 feat(context): improve context provider help text
  lua/CopilotChat/client.lua
Labels: enhancement

#1012 feat(context): improve system command usage guidelines
  lua/CopilotChat/config/contexts.lua
Labels: enhancement

#1013 feat(utils): add binary file filtering in directory scans
  lua/CopilotChat/utils.lua
Labels: enhancement

#1014 feat: add additional binary file types to scan exclusions
  lua/CopilotChat/utils.lua
Labels: enhancement

#1016 fix: handle cancelled jobs in CopilotChat
  lua/CopilotChat/init.lua
Labels: bug

#1018 docs: improve API reference organization and clarity
  README.md
Labels: documentation

#1019 docs: remove # prefix from context provider examples
  README.md
Labels: documentation

#1021 refactor: remove unused similarity threshold parameters
  lua/CopilotChat/context.lua
Labels: refactor

#1022 fix: handle treesitter parsing in fast events
  lua/CopilotChat/utils.lua
Labels: bug

#1024 docs: add missing `,` in default config
  README.md
Labels: documentation

#1027 fix: improve headless mode handling in callbacks
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: bug, regression

#1032 docs(tiktoken): mark tiktoken loading functions as async
  lua/CopilotChat/tiktoken.lua
Labels: documentation

#1031 Respect &splitbelow and &splitright
  lua/CopilotChat/ui/chat.lua
Labels: bug

#1039 fix: add null check for API response
  lua/CopilotChat/client.lua
Labels: bug

#1044 feat: detect .h files as c filetype
  lua/CopilotChat/utils.lua
Labels: enhancement

#1046 refactor: use plenary.filetype for file type detection
  lua/CopilotChat/utils.lua
Labels: enhancement

#1050 fix: properly save prompt in history
  lua/CopilotChat/init.lua
Labels: bug

#1055 feat: use model name and versioning for model selection and switch to gpt-4o-2024-11-20
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#1059 fix: filter out paygo models from Copilot Chat
  lua/CopilotChat/config/providers.lua
Labels: bug

#1072 fix: use --max-depth arg name for ripgrep <14 compat
  lua/CopilotChat/utils.lua
Labels: bug, enhancement
