Repository CopilotC-Nvim/CopilotChat.nvim, pull requests merged in 2025-02, with the labels that each got.

#739 feat: add quickfix list support for chat answers
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#740 feat: improve prompt readability and clarity
  lua/CopilotChat/prompts.lua
Labels: enhancement

#749 feat(context): add support for commit-specific git diffs
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/context.lua
Labels: enhancement

#751 fix: typescript file type matching
  lua/CopilotChat/utils.lua
Labels: bug, upstream

#494 feat: Add support for github marketplace models
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/copilot.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#763 fix: do not auto trigger context input on text changed
  lua/CopilotChat/init.lua
Labels: bug

#759 feat: Refactor how providers are defined and allow custom providers
  README.md
  lua/CopilotChat/client.lua
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#769 fix: improve github pages deployment config
  .github/workflows/deploy-gh-pages.yml
  Gemfile
  _config.yml
  lua/CopilotChat/config/providers.lua
Labels: bug, documentation, enhancement

#774 feat: migrate from Jekyll to Docsify
  .github/workflows/deploy-gh-pages.yml
  .nojekyll
  _config.yml
  index.html
Labels: documentation

#778 fix: add scheduler in register function
  lua/CopilotChat/context.lua
Labels: bug

#779 feat: remove policy field from provider configuration
  lua/CopilotChat/config/providers.lua
Labels: enhancement

#780 feat: switch documentation to dark theme
  index.html
  lua/CopilotChat/client.lua
Labels: documentation

#781 refactor: simplify HTTP headers
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
Labels: enhancement

#783 fix: improve ollama response handling & error tracking
  lua/CopilotChat/client.lua
Labels: bug, enhancement

#785 fix: improve provider handling and model uniqueness
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
Labels: bug, enhancement

#786 fix: change agent/model id provider suffix format
  lua/CopilotChat/client.lua
Labels: bug

#787 refactor(mappings): move callback functions to mapping config
  README.md
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/diff.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#790 docs: reorganize and improve README.md readability
  README.md
Labels: documentation

#791 fix(ollama): use correct module import path
  README.md
Labels: documentation

#792 fix: update system_prompt config reference
  README.md
Labels: documentation

#794 fix(embeddings): improve embedding resolution reliability
  README.md
  lua/CopilotChat/client.lua
  lua/CopilotChat/context.lua
Labels: bug, documentation

#796 refactor: streamline debug info into `info` mapping
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/debug.lua
Labels: documentation, enhancement

#797 docs: add project name and repository info to docsify config
  index.html
Labels: documentation

#798 refactor: Make history fully respect buffer contents
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#799 fix: update embeddings input parameter name
  lua/CopilotChat/config/providers.lua
Labels: bug

#800 refactor(chat): improve yank functionality and types
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/config/prompts.lua
Labels: enhancement

#801 perf: improve file scanning and async input handling
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#805 refactor: make client module stateless
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#806 fix: remove unused model param from context resolving
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/init.lua
Labels: bug

#807 refactor: simplify resolve_embeddings function signature
  lua/CopilotChat/init.lua
Labels: bug

#808 perf: improve file and context matching performance
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#809 refactor(search): improve symbol search and references
  lua/CopilotChat/client.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#810 fix: use proper headers for GitHub models API call
  lua/CopilotChat/config/providers.lua
Labels: enhancement

#811 fix: improve references display in chat UI
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#813 fix: make token counting optional in chat client
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
Labels: bug

#814 docs: Update ollama readme
  README.md
Labels: documentation

#815 fix(context): ensure minimum number of search results
  lua/CopilotChat/client.lua
  lua/CopilotChat/context.lua
Labels: bug, enhancement

#816 refactor(scoring): improve context relevancy scoring
  lua/CopilotChat/context.lua
Labels: enhancement

#818 fix: include entries with zero score in results
  lua/CopilotChat/context.lua
Labels: bug

#820 fix: correct agent handling in chat client
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/init.lua
Labels: bug

#823 feat: add utils.empty() function for checking empty values
  lua/CopilotChat/client.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/utils.lua
Labels: bug, enhancement

#825 fix: add missing selection messages to generated output
  lua/CopilotChat/client.lua
Labels: bug

#826 refactor(http): simplify curl request handling
  README.md
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#827 docs: move examples and providers to wiki
  README.md
Labels: documentation

#830 fix: clear chat selection marks and highlights on reset
  lua/CopilotChat/init.lua
Labels: bug, enhancement

#831 feat: add keyword highlights and improve buffer docs
  README.md
  lua/CopilotChat/health.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
  lua/CopilotChat/utils.lua
Labels: documentation, enhancement

#832 fix: properly escape highlight pattern chars
  lua/CopilotChat/init.lua
Labels: enhancement

#833 refactor: migrate chat history from UI to client layer
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: bug, enhancement

#834 refactor: adjust context scoring values
  lua/CopilotChat/context.lua
Labels: enhancement

#836 refactor: improve code using vim.iter and tbl_map
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/tiktoken.lua
Labels: enhancement

#838 feat: include chat history in embedding query
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#840 feat(prompts): enhance clarity of prompt instructions
  lua/CopilotChat/config/prompts.lua
Labels: bug

#841 fix: update token handling and message ordering
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
Labels: bug

#842 docs: improve dependencies section organization
  README.md
Labels: documentation

#844 feat!: add glob pattern support for file context
  README.md
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#845 refactor(context): improve file search options handling
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/context.lua
Labels: enhancement

#847 docs: add plugin overview section to README
  README.md
Labels: documentation

#848 docs: update feature list with more detailed descriptions
  README.md
Labels: documentation

#849 docs(readme): remove redundant overview heading
  README.md
Labels: documentation

#850 feat: improve chat buffer syntax highlighting
  README.md
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/spinner.lua
Labels: enhancement

#851 fix: improve error handling in embeddings and messages
  lua/CopilotChat/client.lua
  lua/CopilotChat/init.lua
Labels: enhancement

#852 refactor: move embedding cache to context module
  lua/CopilotChat/client.lua
  lua/CopilotChat/context.lua
Labels: enhancement

#857 docs: update Claude version to 3.7 in README
  README.md
Labels: documentation

#859 docs(prompts): clarify code block format in modify prompt
  lua/CopilotChat/config/prompts.lua
Labels: enhancement

#860 refactor(prompts): improve clarity of copilot prompts
  lua/CopilotChat/config/prompts.lua
Labels: enhancement

#863 refactor: improve token file reading with utils
  lua/CopilotChat/config/providers.lua
Labels: enhancement

#866 refactor: replace vim.loop with vim.uv and simplify file checks
  lua/CopilotChat/config/prompts.lua
  lua/CopilotChat/config/providers.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/ui/spinner.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#867 refactor: replace vim.fn functions with vim.fs equivalents
  lua/CopilotChat/client.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#870 feat: add CopilotChatPrompts command
  README.md
  lua/CopilotChat/init.lua
Labels: documentation, enhancement

#871 feat: add configuration to select_prompt function
  README.md
  lua/CopilotChat/init.lua
Labels: documentation, enhancement

#873 feat(ui): add option to control references display mode
  README.md
  lua/CopilotChat/config.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: documentation, enhancement

#874 refactor(models): simplify model listing by using model_picker_enabled
  lua/CopilotChat/client.lua
  lua/CopilotChat/config/providers.lua
Labels: enhancement

#875 fix: improve filename comparison with absolute paths
  lua/CopilotChat/utils.lua
Labels: bug

#876 refactor: use utils functions for filename handling
  lua/CopilotChat/context.lua
  lua/CopilotChat/select.lua
  lua/CopilotChat/ui/chat.lua
Labels: enhancement

#877 fix: properly handle errors in async contexts
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/diff.lua
Labels: bug

#878 feat: enable range support for CopilotChatPrompts
  lua/CopilotChat/init.lua
Labels: enhancement

#879 feat(doc): mark integrations APIs as deprecated
  lua/CopilotChat/actions.lua
  lua/CopilotChat/integrations/fzflua.lua
  lua/CopilotChat/integrations/snacks.lua
  lua/CopilotChat/integrations/telescope.lua
Labels: documentation

#881 docs: add documentation for overriding buf/win options
  README.md
Labels: documentation

#882 refactor: replace plenary scheduler with internal implementation
  lua/CopilotChat/config/contexts.lua
  lua/CopilotChat/config/mappings.lua
  lua/CopilotChat/context.lua
  lua/CopilotChat/init.lua
  lua/CopilotChat/tiktoken.lua
  lua/CopilotChat/utils.lua
Labels: enhancement

#884 fix: switch buffer only after adjusting window options
  lua/CopilotChat/ui/chat.lua
Labels: bug

#885 fix: improve chat window state handling
  lua/CopilotChat/init.lua
  lua/CopilotChat/ui/chat.lua
Labels: bug
